Update wercker.yml

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -4,9 +4,6 @@ build:
     - script:
         name: A step that executes `npm install` command
         code: npm install  
-    - script:
-        name: Create TLS key and cert
-        code: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=nginxsvc/O=nginxsvc"
 
 push-to-releases:
   steps:
@@ -50,13 +47,6 @@ deploy-to-oke:
         token: $KUBERNETES_TOKEN
         insecure-skip-tls-verify: true
         command: create secret docker-registry wrelease --docker-server=wcr.io --docker-username=$WERCKER_APPLICATION_OWNER_NAME --docker-password=$KUBERNETES_TOKEN --docker-email=${WERCKER_APPLICATION_OWNER_NAME}@mail.com --namespace=$WERCKER_APPLICATION_OWNER_NAME
-
-    - kubectl:
-        name: create TLS secret
-        server: $KUBERNETES_MASTER
-        token: $KUBERNETES_TOKEN
-        insecure-skip-tls-verify: true
-        command: create secret tls tls-secret --key $WERCKER_ROOT/tls.key --cert $WERCKER_ROOT/tls.crt --namespace=$WERCKER_APPLICATION_OWNER_NAME
         
     - kubectl:
         name: create deplyoment
@@ -76,14 +66,21 @@ deploy-to-oke:
         insecure-skip-tls-verify: true
         command: create -f $WERCKER_ROOT/ingress.yml --namespace=$WERCKER_APPLICATION_OWNER_NAME
 
-testapp:
+    - kubectl:
+        name: get LoadBalancer public IP address
+        server: $KUBERNETES_MASTER
+        token: $KUBERNETES_TOKEN
+        insecure-skip-tls-verify: true
+        command: get svc -o jsonpath='{.items[*].status.loadBalancer.ingress[*].ip}' --all-namespaces
+
+functional-test:
   steps:
     - script:
         name: Run and Test microservice
         code: |
               mkdir -p "/pipeline"
               node $WERCKER_ROOT/app.js &
-              sleep 10
+              sleep 5
               CREDITSCORE_URL=http://localhost:3000/creditscore
               echo 'Microservice URL=' $CREDITSCORE_URL
               if curl -X POST -H "Content-Type: application/json" -X POST -d '{"firstname":"John","lastname":"Doe","dateofbirth":"01/01/2015","ssn":"111223333"}' $CREDITSCORE_URL | grep "firstname"
@@ -94,21 +91,26 @@ testapp:
                   echo "Test failed"
                   exit -1
               fi
-              sleep 2
+              sleep 1
 
 ui-functional-test:
   box:
-    id: webnicer/protractor-headless
-    cmd: /bin/sh
+    id: peternagy/chrome-protractor-headless-test:node9.2-chrome62
   steps:
     - script:
-        name: Run application and test UI
+        name: Run UI test
         code: | 
-              node $WERCKER_ROOT/app.js &
-              CREDITSCORE_URL=http://localhost:3000/creditscore
-              echo 'Microservice URL=' $CREDITSCORE_URL
-              webdriver-manager start &
-              sleep 5
+              nohup node $WERCKER_ROOT/app.js > creditscoreapp.log &
+              echo 'Application URL to test: http://localhost:3000/creditscore'
               protractor $WERCKER_ROOT/test/protractor.conf.js
-              
+              exit_status=$?
+              echo 'CreditScore app server log :::START'
+              cat creditscoreapp.log
+              echo 'CreditScore app server log :::END'
+              if [ $exit_status -eq 0 ]; then
+                echo "UI test passed"
+              else
+                echo "UI test failed"
+                exit -1
+              fi                
               
